# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
from cd import Ui_creditWindow
from  model import mymodel
class Ui_MainWindow(object):
    selected = []
    selected_clear=[]
    def creditW(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_creditWindow()
        self.ui.setupUi(self.window2)
        self.window2.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-image: url(:/pic/bg.png);\n""background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Top = QtWidgets.QLabel(self.centralwidget)
        self.Top.setGeometry(QtCore.QRect(150, 40, 621, 71))
        font = QtGui.QFont()
        font.setFamily("FC Friday")
        font.setPointSize(20)
        self.Top.setFont(font)
        self.Top.setStyleSheet("background-image: url(:/pic/orgbg.png);")
        self.Top.setObjectName("Top")
        self.faculty_label = QtWidgets.QLabel(self.centralwidget)
        self.faculty_label.setGeometry(QtCore.QRect(110, 180, 41, 16))
        font = QtGui.QFont()
        font.setFamily("FC Friday")
        font.setPointSize(12)
        self.faculty_label.setFont(font)
        self.faculty_label.setObjectName("faculty_label")
        self.faculty_box = QtWidgets.QComboBox(self.centralwidget)
        self.faculty_box.setGeometry(QtCore.QRect(340, 180, 301, 22))
        self.faculty_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.faculty_box.setStyleSheet("background-image: url(:/pic/wbg.png);")
        self.faculty_box.setObjectName("faculty_box")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.faculty_box.addItem("")
        self.price_label = QtWidgets.QLabel(self.centralwidget)
        self.price_label.setGeometry(QtCore.QRect(110, 210, 81, 16))
        font = QtGui.QFont()
        font.setFamily("FC Friday")
        font.setPointSize(12)
        self.price_label.setFont(font)
        self.price_label.setObjectName("price_label")
        self.price_box = QtWidgets.QComboBox(self.centralwidget)
        self.price_box.setGeometry(QtCore.QRect(340, 210, 301, 22))
        self.price_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.price_box.setStyleSheet("background-image: url(:/pic/wbg.png);")
        self.price_box.setObjectName("price_box")
        self.price_box.addItem("")
        self.price_box.addItem("")
        self.price_box.addItem("")
        self.price_box.addItem("")
        self.price_box.addItem("")
        self.price_box.addItem("")
        self.price_box.addItem("")
        self.price_box.addItem("")
        self.purpose_label = QtWidgets.QLabel(self.centralwidget)
        self.purpose_label.setGeometry(QtCore.QRect(110, 240, 91, 21))
        font = QtGui.QFont()
        font.setFamily("FC Friday")
        font.setPointSize(12)
        self.purpose_label.setFont(font)
        self.purpose_label.setObjectName("purpose_label")
        self.purpose1_label = QtWidgets.QLabel(self.centralwidget)
        self.purpose1_label.setGeometry(QtCore.QRect(220, 240, 81, 16))
        font = QtGui.QFont()
        font.setFamily("FC Friday")
        font.setPointSize(12)
        self.purpose1_label.setFont(font)
        self.purpose1_label.setObjectName("purpose1_label")
        self.purpose2_label = QtWidgets.QLabel(self.centralwidget)
        self.purpose2_label.setGeometry(QtCore.QRect(220, 270, 81, 16))
        font = QtGui.QFont()
        font.setFamily("FC Friday")
        font.setPointSize(12)
        self.purpose2_label.setFont(font)
        self.purpose2_label.setObjectName("purpose2_label")
        self.purpose3_label = QtWidgets.QLabel(self.centralwidget)
        self.purpose3_label.setGeometry(QtCore.QRect(220, 300, 81, 16))
        font = QtGui.QFont()
        font.setFamily("FC Friday")
        font.setPointSize(12)
        self.purpose3_label.setFont(font)
        self.purpose3_label.setObjectName("purpose3_label")
        self.purpose1_box = QtWidgets.QComboBox(self.centralwidget)
        self.purpose1_box.setGeometry(QtCore.QRect(340, 240, 301, 22))
        self.purpose1_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.purpose1_box.setStyleSheet("background-image: url(:/pic/wbg.png);")
        self.purpose1_box.setObjectName("purpose1_box")
        self.purpose1_box.addItem("")
        self.purpose1_box.addItem("")
        self.purpose1_box.addItem("")
        self.purpose1_box.addItem("")
        self.purpose1_box.addItem("")
        self.purpose1_box.addItem("")
        self.purpose1_box.addItem("")
        self.purpose1_box.addItem("")
        self.purpose2_box = QtWidgets.QComboBox(self.centralwidget)
        self.purpose2_box.setGeometry(QtCore.QRect(340, 270, 301, 22))
        self.purpose2_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.purpose2_box.setStyleSheet("background-image: url(:/pic/wbg.png);")
        self.purpose2_box.setObjectName("purpose2_box")
        self.purpose2_box.addItem("")
        self.purpose2_box.addItem("")
        self.purpose2_box.addItem("")
        self.purpose2_box.addItem("")
        self.purpose2_box.addItem("")
        self.purpose2_box.addItem("")
        self.purpose2_box.addItem("")
        self.purpose2_box.addItem("")
        self.purpose2_box.addItem("")
        self.purpose3_box = QtWidgets.QComboBox(self.centralwidget)
        self.purpose3_box.setGeometry(QtCore.QRect(340, 300, 301, 22))
        self.purpose3_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.purpose3_box.setStyleSheet("background-image: url(:/pic/wbg.png);")
        self.purpose3_box.setObjectName("purpose3_box")
        self.purpose3_box.addItem("")
        self.purpose3_box.addItem("")
        self.purpose3_box.addItem("")
        self.purpose3_box.addItem("")
        self.purpose3_box.addItem("")
        self.purpose3_box.addItem("")
        self.purpose3_box.addItem("")
        self.purpose3_box.addItem("")
        self.purpose3_box.addItem("")
        self.freaquency_label = QtWidgets.QLabel(self.centralwidget)
        self.freaquency_label.setGeometry(QtCore.QRect(110, 330, 221, 21))
        font = QtGui.QFont()
        font.setFamily("FC Friday")
        font.setPointSize(12)
        self.freaquency_label.setFont(font)
        self.freaquency_label.setObjectName("freaquency_label")
        self.freaquecy_box = QtWidgets.QComboBox(self.centralwidget)
        self.freaquecy_box.setGeometry(QtCore.QRect(340, 330, 301, 22))
        self.freaquecy_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.freaquecy_box.setStyleSheet("background-image: url(:/pic/wbg.png);")
        self.freaquecy_box.setObjectName("freaquecy_box")
        self.freaquecy_box.addItem("")
        self.freaquecy_box.addItem("")
        self.freaquecy_box.addItem("")
        self.freaquecy_box.addItem("")
        self.freaquecy_box.addItem("")
        self.predictbtn = QtWidgets.QPushButton(self.centralwidget)
        self.predictbtn.setGeometry(QtCore.QRect(350, 390, 100, 30))
        self.predictbtn.setStyleSheet("background-image: url(:/pic/wbg.png);")
        self.predictbtn.setObjectName("predictbtn")
        self.faculty_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.faculty_label_2.setGeometry(QtCore.QRect(110, 150, 41, 16))
        font = QtGui.QFont()
        font.setFamily("FC Friday")
        font.setPointSize(12)
        self.faculty_label_2.setFont(font)
        self.faculty_label_2.setObjectName("faculty_label_2")
        self.gender_box = QtWidgets.QComboBox(self.centralwidget)
        self.gender_box.setGeometry(QtCore.QRect(340, 150, 301, 22))
        self.gender_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gender_box.setStyleSheet("background-image: url(:/pic/wbg.png);")
        self.gender_box.setObjectName("gender_box")
        self.gender_box.addItem("")
        self.gender_box.addItem("")
        self.gender_box.addItem("")
        self.gender_box.addItem("")
        self.creditbtn = QtWidgets.QPushButton(self.centralwidget)
        self.creditbtn.setGeometry(QtCore.QRect(670, 540, 100, 30))
        self.creditbtn.setStyleSheet("background-image: url(:/pic/wbg.png);")
        self.creditbtn.setObjectName("creditbtn")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.predictbtn.clicked.connect(self.rev_in)
        self.creditbtn.clicked.connect(self.creditW)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "โปรแกรมทำนายการเลือกซื้ออุปกรณ์อิเล็กทรอนิกส์"))
        self.Top.setText(_translate("MainWindow", "โปรแกรมทำนายการเลือกซื้ออุปกรณ์อิเล็กทรอนิกส์"))
        self.faculty_label.setText(_translate("MainWindow", "คณะ"))
        self.faculty_box.setItemText(0, _translate("MainWindow", "-----------------------เลือกคณะ-----------------------"))
        self.faculty_box.setItemText(1, _translate("MainWindow", "วิศวกรรมศาสตร์"))
        self.faculty_box.setItemText(2, _translate("MainWindow", "สถาปัตยกรรมศาสตร์"))
        self.faculty_box.setItemText(3, _translate("MainWindow", "วิทยาศาสตร์"))
        self.faculty_box.setItemText(4, _translate("MainWindow", "ครุศาสตร์อุตสาหกรรมและเทคโนโลยี"))
        self.faculty_box.setItemText(5, _translate("MainWindow", "เทคโนโลยีการเกษตร"))
        self.faculty_box.setItemText(6, _translate("MainWindow", "เทคโนโลยีสารสนเทศ"))
        self.faculty_box.setItemText(7, _translate("MainWindow", "อุตสาหกรรมอาหาร"))
        self.faculty_box.setItemText(8, _translate("MainWindow", "บริหารธุรกิจ"))
        self.faculty_box.setItemText(9, _translate("MainWindow", "ศิลปศาสตร์"))
        self.faculty_box.setItemText(10, _translate("MainWindow", "แพทยศาสตร์"))
        self.faculty_box.setItemText(11, _translate("MainWindow", "วิทยาลัยนาโนเทคโนโลยีพระจอมเกล้าลาดกระบัง"))
        self.faculty_box.setItemText(12, _translate("MainWindow", "วิทยาลัยนวัตกรรมการผลิตขั้นสูง"))
        self.faculty_box.setItemText(13, _translate("MainWindow", "วิทยาลัยอุตสาหกรรมการบินนานาชาติ"))
        self.faculty_box.setItemText(14, _translate("MainWindow", "วิทยาลัยวิจัยนวัตกรรมทางการศึกษา"))
        self.faculty_box.setItemText(15, _translate("MainWindow", "วิทยาลัยวิศวกรรมสังคีต"))
        self.price_label.setText(_translate("MainWindow", "งบประมาณ"))
        self.price_box.setItemText(0, _translate("MainWindow", "--------------------เลือกงบประมาณ--------------------"))
        self.price_box.setItemText(1, _translate("MainWindow", "น้อยกว่า 5,000 บาท"))
        self.price_box.setItemText(2, _translate("MainWindow", "5,001 - 10,000 บาท"))
        self.price_box.setItemText(3, _translate("MainWindow", "10,001 - 15,000 บาท"))
        self.price_box.setItemText(4, _translate("MainWindow", "15,001 - 20,000 บาท"))
        self.price_box.setItemText(5, _translate("MainWindow", "20,001 - 25,000 บาท"))
        self.price_box.setItemText(6, _translate("MainWindow", "25,001 - 30,000 บาท"))
        self.price_box.setItemText(7, _translate("MainWindow", "มากกว่า 30,000 บาท"))
        self.purpose_label.setText(_translate("MainWindow", "วัตถุประสงค์"))
        self.purpose1_label.setText(_translate("MainWindow", "ลำดับที่ 1"))
        self.purpose2_label.setText(_translate("MainWindow", "ลำดับที่ 2"))
        self.purpose3_label.setText(_translate("MainWindow", "ลำดับที่ 3"))
        self.purpose1_box.setItemText(0, _translate("MainWindow", "-----------------------ลำดับที่ 1-----------------------"))
        self.purpose1_box.setItemText(1, _translate("MainWindow", "เล่นเกม"))
        self.purpose1_box.setItemText(2, _translate("MainWindow", "การศึกษา"))
        self.purpose1_box.setItemText(3, _translate("MainWindow", "วาดรูป"))
        self.purpose1_box.setItemText(4, _translate("MainWindow", "ตัดต่อวิดีโอ"))
        self.purpose1_box.setItemText(5, _translate("MainWindow", "เขียนแบบ , ออกแบบแผนผังต่าง ๆ"))
        self.purpose1_box.setItemText(6, _translate("MainWindow", "เขียนโปรแกรม"))
        self.purpose1_box.setItemText(7, _translate("MainWindow", "สื่อบันเทิง (สตรีมมิ่งเพลงและวิดีโอต่าง ๆ)"))
        self.purpose2_box.setItemText(0, _translate("MainWindow", "-----------------------ลำดับที่ 2-----------------------"))
        self.purpose2_box.setItemText(1, _translate("MainWindow", "เล่นเกม"))
        self.purpose2_box.setItemText(2, _translate("MainWindow", "การศึกษา"))
        self.purpose2_box.setItemText(3, _translate("MainWindow", "วาดรูป"))
        self.purpose2_box.setItemText(4, _translate("MainWindow", "ทำเพลง"))
        self.purpose2_box.setItemText(5, _translate("MainWindow", "ตัดต่อวิดีโอ"))
        self.purpose2_box.setItemText(6, _translate("MainWindow", "เขียนแบบ , ออกแบบแผนผังต่าง ๆ"))
        self.purpose2_box.setItemText(7, _translate("MainWindow", "เขียนโปรแกรม"))
        self.purpose2_box.setItemText(8, _translate("MainWindow", "สื่อบันเทิง (สตรีมมิ่งเพลงและวิดีโอต่าง ๆ)"))
        self.purpose3_box.setItemText(0, _translate("MainWindow", "-----------------------ลำดับที่ 3-----------------------"))
        self.purpose3_box.setItemText(1, _translate("MainWindow", "เล่นเกม"))
        self.purpose3_box.setItemText(2, _translate("MainWindow", "การศึกษา"))
        self.purpose3_box.setItemText(3, _translate("MainWindow", "วาดรูป"))
        self.purpose3_box.setItemText(4, _translate("MainWindow", "ทำเพลง"))
        self.purpose3_box.setItemText(5, _translate("MainWindow", "ตัดต่อวิดีโอ"))
        self.purpose3_box.setItemText(6, _translate("MainWindow", "เขียนแบบ , ออกแบบแผนผังต่าง ๆ"))
        self.purpose3_box.setItemText(7, _translate("MainWindow", "เขียนโปรแกรม"))
        self.purpose3_box.setItemText(8, _translate("MainWindow", "สื่อบันเทิง (สตรีมมิ่งเพลงและวิดีโอต่าง ๆ)"))
        self.freaquency_label.setText(_translate("MainWindow", "ความถี่ในการพกพา (ต่อสัปดาห์)"))
        self.freaquecy_box.setItemText(0, _translate("MainWindow", "----------------เลือกความถี่ในการพกพา----------------"))
        self.freaquecy_box.setItemText(1, _translate("MainWindow", "ทุกวัน"))
        self.freaquecy_box.setItemText(2, _translate("MainWindow", "3 - 5 วัน"))
        self.freaquecy_box.setItemText(3, _translate("MainWindow", "1 - 2 วัน"))
        self.freaquecy_box.setItemText(4, _translate("MainWindow", "ไม่พกพาเลย"))
        self.predictbtn.setText(_translate("MainWindow", "ทำนาย"))
        self.faculty_label_2.setText(_translate("MainWindow", "เพศ"))
        self.gender_box.setItemText(0, _translate("MainWindow", "-----------------------เลือกเพศ-----------------------"))
        self.gender_box.setItemText(1, _translate("MainWindow", "ชาย"))
        self.gender_box.setItemText(2, _translate("MainWindow", "หญิง"))
        self.gender_box.setItemText(3, _translate("MainWindow", "LGBTQ+"))
        self.creditbtn.setText(_translate("MainWindow", "ผู้จัดทำ"))
    
    def clear_selected(self,selected,selected_clear):
        self.selected=self.selected_clear.copy()
        
    def rev_in(self):
        check_emp = self.checkNull()
        if(check_emp):
            self.alert()
        else:  
            gender = self.gender_box.currentText()
            self.selected.append(gender)
            faculty = self.faculty_box.currentText()
            self.selected.append(faculty)
            price = self.price_box.currentText()
            self.selected.append(price)
            purpose1 = self.purpose1_box.currentText()
            self.selected.append(purpose1)
            purpose2 = self.purpose2_box.currentText()
            self.selected.append(purpose2)
            purpose3 = self.purpose3_box.currentText()
            self.selected.append(purpose3)
            freaquency = self.freaquecy_box.currentText()
            self.selected.append(freaquency)
            print(self.selected)
            self.predict()
            print('---------------------------------------------------------------------------------------------------')

    def checkNull(self):
        check = False
        g_index = self.gender_box.currentIndex()
        f_index = self.faculty_box.currentIndex()
        p_index = self.price_box.currentIndex()
        pp1_index = self.purpose1_box.currentIndex()
        pp2_index = self.purpose2_box.currentIndex()
        pp3_index = self.purpose3_box.currentIndex()
        fq_index = self.freaquecy_box.currentIndex()
        index_list = [g_index,f_index,p_index,pp1_index,pp2_index,pp3_index,fq_index]
        print(index_list)
        for i in index_list:
            if(i==0):
                check = True
        return(check)
    
    def alert(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Warning)
        msg.setWindowTitle("Alert")
        msg.setText("กรุณาเลือกข้อมูลให้ครบ")
        x = msg.exec_()
    
    
        
    def predict(self):
        self.Dmodel = mymodel(self.selected)
        ans=self.Dmodel.calculate()
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setWindowTitle("Result")
        if(ans==0):
            msg.setText("ผลลัพธ์ : Laptop")
        elif(ans==1):
            msg.setText("ผลลัพธ์ : Tablet")
        x = msg.exec_()
        self.clear_selected(self.selected,self.selected_clear)
        
import myimage_rc
from PyQt5.QtWidgets import QMessageBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())




